# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Content Orchestration Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  	
  # Pods for Content Orchestration Example
  pod 'Thunderhead', :git => 'https://github.com/thunderheadone/one-sdk-ios.git', :tag => '2.23.1'
end
