# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dynamic Initialization Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dynamic Initialization Example
  pod 'Thunderhead', :git => 'https://github.com/thunderheadone/one-sdk-ios.git', :tag => '5.0.0'
  
  target 'Dynamic Initialization ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dynamic Initialization ExampleUITests' do
    # Pods for testing
  end

end
